let emotes = {
    "ahegao": "ahegao.png",
    "ahhhhhhhhh": "ahhhhhhhhh.gif",
    "amusing" :"amusing.png",
    "awesome": "awesome.png",
    "blush" : "blush.png",
    "bread" : "bread.png",
    "camera" : "camera.png",
    "care" : "care.png",
    "coffee" : "coffee.png",
    "cookie" : "cookie.png",
    "crying-cool" :"crying-cool.png",
    "crying-laughing" :"crying-laughing.png",
    "dab": "dab.gif",
    "dank": "dank-engine.png",
    "disappointed" : "disappointed.png",
    "flame-thrower" : "flame-thrower.png",
    "god-why" :"god-why.png",
    "goofy" :"goofy.png",
    "guillaume": "guillaume.png",
    "headache" : "headache.png",
    "heart-druel" :"heart-druel.png",
    "hitting-a-yeet" :"hitting-a-yeet.png",
    "honkler": "honkler.png",
    "jerry": "jerry.png",
    "knife" : "knife.png",
    "like": "like.png",
    "mathieu": "mathieu.jpg",
    "melt" : "melt.png",
    "nicolas": "nicolas.png",
    "ok-drops" :"ok-drops.png",
    "party-meow" : "party-meow.gif",
    "party-parrot" : "party-parrot.gif",
    "pary-blob": "party-blob.gif",
    "peek" : "peek.png",
    "pepe-christ": "pepe-christ.png",
    "pepe-dawae": "pepe-dawae.png",
    "pepe-festive": "pepe-festive.png",
    "pepe-hands": "pepe-hands.png",
    "pepe-happy": "pepe-happy.png",
    "pepe-hmm": "pepe-hmm.png",
    "pepe-kms": "pepe-kms.png",
    "pepe-link": "pepe-link.png",
    "pepe-ok": "pepe-ok.png",
    "pepe-panties": "pepe-panties.png",
    "pepe-ping": "pepe-ping.png",
    "pepe-reeeee": "pepe-reeeee.png",
    "pepe-stab": "pepe-stab.png",
    "pepe-sweating": "pepe-sweating.png",
    "pepe-thor": "pepe-thor.png",
    "pepe-yikes": "pepe-yikes.png",
    "popsicle" : "popsicle.png",
    "rain": "rain.gif",
    "rainbow-dumb" :"rainbow-dumb.png",
    "shocked" : "shocked.png",
    "shooter" :"shooter.png",
    "sip" : "sip.png",
    "the-mad-man" :"the-mad-man.png",
    "thonk": "thonk.jpg",
    "typing" : "typing.gif",
    "wow-meow" : "wow-meow.png",
    "wow": "wow.png",
    "yeetus" :"yeetus.png",
}

export {emotes as default};